resolution: 0.04
map_length: 4
dilation_size: 3
sensor_noise_factor: 0.05
mahalanobis_thresh: 2.0
outlier_variance: 0.01
time_variance: 0.01
max_variance: 100.0
initial_variance: 100.0
traversability_inlier: 0.1
dilation_size: 2
wall_num_thresh: 100
min_height_drift_cnt: 100
position_noise_thresh: 0.1
position_lowpass_alpha: 0.4

gather_mode: 'mean'
enable_edge_sharpen: true
enable_drift_compensation: true
enable_pointcloud_publishing: true

weight_file: 'config/weights.yaml'

pointcloud_topics: ['/realsense_d435_front/depth/color/points',
                    '/realsense_d435_rear/depth/color/points']
pose_topic: '/state_estimator/pose_in_odom'
map_frame: 'odom'
